version: '3.8'
services:
    golang:
      build: 
        context: .
        dockerfile: ./Dockerfile.user_service
      env_file:
        - .env
      volumes:
      - .:/usr/src/app
      ports:
        - '8080:23450'
    postgres:
      container_name: postgresql
      environment:
          - POSTGRES_USER=myusername
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      image: postgres
      volumes:
        - postgres-db:/var/lib/postgresql/data
      ports:
        - '5431:5432'
volumes:
  postgres-db: